"""initial tables

Revision ID: 7d41656fa0ac
Revises: 4c69cb26ffa9
Create Date: 2026-03-24 10:08:08.945983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d41656fa0ac'
down_revision = '4c69cb26ffa9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
